services:
  frontend:
    build: frontend/
    ports:
      - 8080:8080
    environment:
      - BACKEND_URL=backend:3000
  backend:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
